# Generated by Django 2.1.2 on 2018-10-09 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20181008_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='image',
            field=models.CharField(default='images/goods/goods003.jpg', max_length=200, verbose_name='分类展示的图片'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='number',
            field=models.IntegerField(default=0, verbose_name='排序字段'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 9, 15, 31, 24, 30330), verbose_name='创建时间'),
        ),
    ]
