# Generated by Django 2.1.2 on 2018-10-09 09:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_auto_20181009_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goods.CategoryModel', verbose_name='商品的分类'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 9, 17, 58, 41, 57424), verbose_name='创建时间'),
        ),
    ]
