# Generated by Django 2.1.2 on 2018-10-10 01:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_auto_20181009_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsmodel',
            name='popular',
            field=models.IntegerField(default=0, verbose_name='人气指数'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 10, 9, 32, 13, 793197), verbose_name='创建时间'),
        ),
    ]
