# Generated by Django 2.1.2 on 2018-10-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180929_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectgoodsmodel',
            name='detail_address',
            field=models.CharField(max_length=200, verbose_name='详细地址'),
        ),
    ]
