# Generated by Django 2.1.2 on 2018-10-08 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20180929_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 8, 11, 2, 29, 612566), verbose_name='创建时间'),
        ),
    ]
